### ISSUE TITLE
Pieces ask command not working

### ISSUE THREAD

**Issue by shivay-at-pieces** [pieces-app/cli-agent#125]
<img width="1150" alt="image" src="https://github.com/pieces-app/cli-agent/assets/143828586/6a1f242c-844f-47e1-b1a3-ce461550bb91">

**Comment by Bishoy-at-pieces** [comment]
Hey Shivay thank you for reporting that issue. 
I think the wrong dependency is downloaded you should download websocket-client instead of websocket
to solve this issue you need to do

`pip uninstall websocket-client`
`pip uninstall websocket`
then 
`pip install websocket-client`

let me know how it goes
